### ISSUE TITLE
Tor users are blocked?

### ISSUE THREAD

**Issue by Gert-dev** [cloudrac3r/cadencegq#13]
Hello

It appears Tor users or Tor IP addresses are actively blocked from cadence.gq as well as cadence.moe. I was wondering if this was on purpose? FWIW, Invidious and the other used domains appear to work fine on Tor.

The following message is displayed:

```
403 Forbidden
nginx/1.10.3 (Ubuntu)
```

It works fine when Tor is disabled.

EDIT: It appears not all addresses are blocked, only some are. Perhaps it's a security measure kicking in, but not a blanket block or blacklist of all Tor endpoints.

**Comment by cloudrac3r** [comment]
In the past I was receiving abuse from people connected over Tor and had to block Tor as a whole so that the site would continue to function normally for everone else. I agree that it could be done _nicer,_ but I just didn't have the energy to deal with it at the time.

I'm not interested in allowing people on Tor access to anything under /cloudtube/.

**Comment by Gert-dev** [comment]
Okay, thanks for responding. At least through this ticket the reasons are clear and easy for others to find.

Also, thanks for maintaining this!

**Comment by cloudrac3r** [comment]
I've revised this and Tor users are only blocked when trying to access addresses under /cloudtube, and they see a page that explains what has happened.

**Comment by GitWaifu** [comment]
rather ironic how the man that helps tor users to watch youtube through invidious also blocks the same people from using his own youtube proxy

**Comment by cloudrac3r** [comment]
What?

Also, I'm not a man.

**Comment by GitWaifu** [comment]
you should go back to your home planet then
