### ISSUE TITLE
No accentuated characters

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cloudrac3r/cadencegq#4]
Hi,

I don't know if it's the right place to put this but I think I found a bug.

If on cloudtube I look for "test" it works fine but for "tést" (url : https://cadence.gq/cloudtube/search?q=t%C3%A9st&order=relevance )then I get *Error requesting data from Invidious*.

Given that invidious returns results for "tést" (url : https://invidio.us/search?q=t%C3%A9st) I think the problem is on your side.

Thanks for reading this :)

**Comment by cloudrac3r** [comment]
Did some reading and it's possibly a bug in node.js. https://github.com/nodejs/node/issues/13296

The response from the HTTP server says the requested path is `/cloudtube/search?q=t��st&sort_by=relevance`. That's right: two instances of U+FFFD OBJECT REPLACEMENT CHARACTER.

From what I can tell, this isn't due to any badly coded interpretation of mine, but rather this is all the data that the HTTP server gives me. It's not possible to reconstruct the original path.

The previously linked issue is fixed in node.js v11+, so I'll try upgrading to that and see if it's fixed.

**Comment by cloudrac3r** [comment]
Upgraded node.js to v11.2.0 and nothing changed. Not sure what to do now. Guess I'll take a closer look.

**Comment by thiswillbeyourgithub** [comment]
I'm not sure but I think I also had the same error while searching for keywords separated by a space like "a b c", I don't know if it was related to it but replacing the space in the adresse url with a plus seemed to solve it (""a+b+c"). It happened a few times for a while but nothing really predictable

**Comment by cloudrac3r** [comment]
I've never had an issue with spaces in searches. If it happens again, I'd appreciate a screenshot and the specific URL that didn't work.

**Comment by thiswillbeyourgithub** [comment]
I'll keep that in mind but I don't spend that much time on youtube at this part of the year :/

**Comment by cloudrac3r** [comment]
Fixed the original issue with [#252f6e3](https://github.com/cloudrac3r/cadencegq/commit/252f6e38794d2e3c1f80be4d83fe8579a47b3620). Enjoy!

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot ! Please feel great today <3

**Comment by cloudrac3r** [comment]
Will do my best ;)
