### ISSUE TITLE
Thumbnails missing.

### ISSUE THREAD

**Issue by ghost** [cloudrac3r/cadencegq#7]
In CloudTube, the video thumbnails are not displaying. Its just missing. Otherwise fantastic.

**Comment by cloudrac3r** [comment]
Can not reproduce.

Thumbnail images are served from another domain (either Google or Invidious), so I assume that a content blocker extension has blocked access to those images.

Checking uBlock Origin, Privacy Badger, and Disconnect, none of them block access to the ytimg domain. If you're using uMatrix, you should check the settings in that.

You should also try going to [the settings page](https://cadence.moe/cloudtube/settings) and looking under the "privacy & history" section for the checkbox "Use Invidious to proxy thumbnails". Checking this box (I believe it's checked by default?) will serve thumbnails from the Invidious domain, which has a do not track policy (improvement over YouTube's policies), but is subject to images loading more slowly and is dependent on Invidious being online (which it should always be).

You could playing with that checkbox to see if it fixes or breaks thumbnails, but I believe the real issue is a content blocker.

**Comment by ghost** [comment]
Hi! I determined the source of the issue. Many theme engines for the browser seem to cause the thumbnail images to disappear. I think it's possible to fix this. Anyway, thanks for the quick response!
